development:
  access_key_id: AKIAJ7ETWWKM5NUPWAZA
  secret_access_key: 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

production:
  access_key_id: AKIAJ7ETWWKM5NUPWAZA
  secret_access_key: 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